[package]
name = "psvm"
version = "0.1.1"
description = "A tool to manage and update the Polkadot SDK dependencies in any Cargo.toml file."
repository = "https://github.com/paritytech/psvm"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
license = "Apache-2.0 OR GPL-3.0"

[dependencies]
clap = "3.0"
toml_edit = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.21"
env_logger = "0.11.3"
