[package]
name = "psvm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
license = "Apache-2.0 OR GPL-3.0"

[dependencies]
clap = "3.0"
toml_edit = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
