name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --locked
    
    - name: Run tests
      run: cargo test --locked

    - name: Polkadot Runtimes Work
      run: |
        cargo install --path . --locked
        git clone --depth 1 --branch main https://github.com/polkadot-fellows/runtimes
        cd runtimes
        
        # Some testing
        psvm -v stable2407
        psvm -v stable2407-2
        psvm -v 1.13.0
        psvm -l
